### TODO: FIX ME! ###
# name: Security

# on: [push, pull_request]

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Gitleaks
#       uses: zricethezav/gitleaks-action@master
