name: Security

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Gitleaks
      uses: zricethezav/gitleaks-action@master
    - name: Snyk
      uses: snyk/actions@0.1.1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
