# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
    - run: npm run jest -- -u
